name: Testes de Unidade em um projeto NodeJS e Fastify
 
on:
  push:
    # Branches que desejo proteger
    branches: [ main ]

jobs:
  test-unities:
    
    # runner (Maquina virtual que será alocada pelo github p/ rodar o job)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Usar Node 18.x
        # Cria uma action p/ que o node seja configurado
        uses: actions/setup-node@v3
          with:
            node-version: '18.x'
      - name: Instalar dependencias  
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Rodar os testes de unidade com JEST 
      - run: npm test    




