name: Testes de Unidade em um projeto NodeJS e Fastify
 
on:
  push:
    branches: [ main ]

jobs:
  test-unities:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Usar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instalar dependencias  
        run: npm install
      - name: Build
        run: npm run build
      - name: Rodar os testes de unidade com JEST 
        run: npm test    




